### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by john-g-g** [steemit/jussi#72]
View details in Rollbar: [https://rollbar.com/Steemit/jussi/items/1/](https://rollbar.com/Steemit/jussi/items/1/)

```
Traceback (most recent call last):
  File "/Users/muyloco/Dev/steemit/jussi/.venv/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/Users/muyloco/Dev/steemit/jussi/jussi/handlers.py", line 42, in handle_jsonrpc
    jsonrpc_requests)
  File "/Users/muyloco/Dev/steemit/jussi/jussi/handlers.py", line 174, in dispatch_single
    batch_index)
  File "/Users/muyloco/Dev/steemit/jussi/jussi/utils.py", line 65, in async_retry
    raise e
  File "/Users/muyloco/Dev/steemit/jussi/jussi/utils.py", line 58, in async_retry
    return await call()
  File "/Users/muyloco/Dev/steemit/jussi/jussi/utils.py", line 73, in update_last_irreversible_block_num
    raise e
  File "/Users/muyloco/Dev/steemit/jussi/jussi/utils.py", line 71, in update_last_irreversible_block_num
    json_response = await call()
  File "/Users/muyloco/Dev/steemit/jussi/jussi/handlers.py", line 86, in fetch_ws
    raise TypeError
TypeError
```

**Comment by john-g-g** [comment]
integration test
