### ISSUE TITLE
Lots of error messages from jussi calling from steem-js

### ISSUE THREAD

**Issue by prcolaco** [steemit/jussi#88]
Lately I started getting a lot of errors returned from steem-js calls to jussi, that I do not get if connected to other api nodes.

The most frequent and that makes jussi almost unusable for me is:
```
{ code: -32603,
   message: 'Internal Error',
   data:
    { error_id: 'fae53c61-4afe-4512-8a78-2c36f5b89449',
      request:
       { amzn_trace_id: 'Root=1-5a5ce40d-15932738218531a67b099feb',
         jussi_request_id: '1516037133.745-24093832-418-172.31.9.230-94.62.9.133' } } }
```
This happens mostly with streamOperations() calls, after the first chuck or two, and aborts the stream...

Then from time to time I get this error on other calls, even on getContent():
```
{ FetchError: invalid json response body at https://api.steemit.com reason: Unexpected token < in JSON at position 0
     at ./node_modules/node-fetch/lib/body.js:48:31
     at tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:693:18)
     at Async._drainQueue (./node_modules/bluebird/js/release/async.js:133:16)
     at Async._drainQueues (./node_modules/bluebird/js/release/async.js:143:10)
     at Immediate.Async.drainQueues (./node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:789:20)
     at tryOnImmediate (timers.js:751:5)
     at processImmediate [as _immediateCallback] (timers.js:722:5)
   name: 'FetchError',
   message: 'invalid json response body at https://api.steemit.com reason: Unexpected token < in JSON at position 0',
   type: 'invalid-json' }
```

If you need any further info, please ping me...

**Comment by sneak** [comment]
Could you please provide a gist or a test script that reproduces the issue reliably?

**Comment by febinkk** [comment]
I am getting this frequently, (not always)

   {'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal Error', 'data': {'error_id': '4ea0a023-3e8d-42c4-b244-f21776efad92', 'request': {'amzn_trace_id': 'Root=1-5a6075b6-24fd5b487639d7864f0913cc', 'jussi_request_id': '1516271030.097-11034873-759-172.31.52.90-106.66.171.171'}}}, 'id': 1277}

While using 'network_broadcast_api' and  'broadcast_transaction()' from a custom python client.

This doesn't always fail, so difficult to reproduce reliably, though **it looks like there is a correlation with time of the day.**

**Comment by prcolaco** [comment]
That’s exactly what @febinkk said, it is correlated with load or something... Any script that performs votes will get these ‘Internal errors’. Even on DSound people have been reporting that from time to time the vote doesn’t work... The invalid Json error happens on operations like getContent(), mainly on the same load occasions.
